name: CrystaLearn Dev CD

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]

jobs:
  build_and_deploy_dev:
    name: build and deploy to develop env
    uses: ./.github/workflows/cd-template.yml
    with:
      ENV_NAME: Develop
    secrets: inherit